packages:
  - apps/*
  - packages/*

allowBuilds:
  electron-winstaller: true
  sharp: true

confirmModulesPurge: false
engineStrict: true
sharedWorkspaceLockfile: true
strictPeerDependencies: true
verifyDepsBeforeRun: error
